### ISSUE TITLE
installing 

### ISSUE THREAD

**Issue by Pillhead2007** [LuzProject/luz#2]
[*] Installing luz...
[!] Failed to install luz: Command 'pip install https://github.com/LuzProject/luz/archive/refs/heads/main.zip' returned non-zero exit status 127.

any ideas how to fix?

**Comment by ja1dan** [comment]
Hi, what OS would you happen to be running this on?

**Comment by Pillhead2007** [comment]
I tried to install it on Mac OS X Ventura 13.2.1 then I tried windows 11 I’ve just not tried it on Linux:Ubuntu/kali Linux

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ja1dan** [comment]
The current install script should work on macOS as long as you have a python version that is greater than 3.7. As for Windows, WSL (Windows Subsystem for Linux) is needed as Luz uses components that aren't supported on Windows.

**Comment by Pillhead2007** [comment]
That could be the reason why I do have Python 3 don’t know which versions and I have wsl / Ubuntu and kali Linux would I need to load it into Linux environment ? Thanks for the info

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ja1dan** [comment]
Yes, for Windows install you need to be in the WSL shell.

**Comment by Pillhead2007** [comment]
installed the latest python on Mac Ventura 13.2.1 still saying failed to install, how ever it worked on wsl but can't find directory of the file saved it installs but won't run

**Comment by Pillhead2007** [comment]
managed to get it to install and call from wsl how ever getting this error now ?

Traceback (most recent call last):
  File "/home/goldfinch/.local/lib/python3.10/site-packages/luz/__main__.py", line 63, in main
    assign_module(args.type)
  File "/home/goldfinch/.local/lib/python3.10/site-packages/luz/luzgen/modules/modules.py", line 17, in assign_module
    return Tweak()
  File "/home/goldfinch/.local/lib/python3.10/site-packages/luz/luzgen/modules/tweak.py", line 64, in __init__
    self.write_to_file(folder)
  File "/home/goldfinch/.local/lib/python3.10/site-packages/luz/luzgen/modules/module.py", line 77, in write_to_file
    self.tar.decompress_archive(self.template_path, path.parent)
  File "/home/goldfinch/.local/lib/python3.10/site-packages/luz/common/tar.py", line 74, in decompress_archive
    raise Exception(f"Specified archive {archive_name} does not exist.")
Exception: Specified archive /home/goldfinch/.local/lib/python3.10/site-packages/luz/luzgen/templates/tweak/swift.tar.gz does not exist.

[!] An error occured: Specified archive /home/goldfinch/.local/lib/python3.10/site-packages/luz/luzgen/templates/tweak/swift.tar.gz does not exist.

sorry to be a pain

**Comment by ja1dan** [comment]
Yeah, this one is my bad; I have a local patch but I havent pushed it yet. I'll let you know when its working

**Comment by Pillhead2007** [comment]
Okies thanks if I run into any more errors will let you known

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ja1dan** [comment]
Hi!

If you try running the following commands:
```pip uninstall -y luz && rm -rf ~/.luz && python3 -c "$(curl -fsSL https://install-luz.jaidan.dev)" --ref="new-format"```
The issues should be resolved. Keep me posted!

**Comment by Pillhead2007** [comment]
seems to have installed correctly, set up my params for tweak cd into tweak, run luz.py ? Traceback (most recent call last):
  File "/home/goldfinch/pill/luz.py", line 1, in <module>
    from luz import Control, Module
  File "/home/goldfinch/pill/luz.py", line 1, in <module>
    from luz import Control, Module
ImportError: cannot import name 'Control' from partially initialized module 'luz' (most likely due to a circular import) (/home/goldfinch/pill/luz.py)
just so you know i havent got a clue how to make tweaks or ewt i was just lookin for an easy way to make tweaks rather than theos was looking into that before this new way popped up on idownloadblog.com
